version: '3.1'
services:
    webserver:
        build:
            context: ./apache2-docker/
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
        environment:
            VIRTUAL_HOST: probaaho.shuhanmirza.com
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: probaaho.shuhanmirza.com
            LETSENCRYPT_EMAIL: shuhan.mirza@gmail.com

networks:
    default:
        external:
            name: nginx-proxy
    
volumes:
    data: